export interface Person {
  name: string;
  age: number;
}

export function getPersons(): Person[] {
  return [
    { age: 30, name: 'Kelly Lewis' },
    { age: 41, name: 'Frances Barnes' },
    { age: 72, name: 'Debra Adams' },
    { age: 55, name: 'Kevin Reed' },
    { age: 28, name: 'Doris Alexander' },
    { age: 51, name: 'Wanda Stewart' },
    { age: 39, name: 'Carlos Rivera' },
    { age: 66, name: 'Richard Morris' },
    { age: 26, name: 'Jennifer Peterson' },
    { age: 59, name: 'Pamela Mitchell' },
    { age: 43, name: 'Rachel Foster' },
    { age: 31, name: 'Deborah Martinez' },
    { age: 36, name: 'Chris Rodriguez' },
    { age: 21, name: 'Anne Davis' },
    { age: 40, name: 'Kenneth Richardson' },
    { age: 55, name: 'John Patterson' },
    { age: 42, name: 'Paula Butler' },
    { age: 33, name: 'Mark Powell' },
    { age: 35, name: 'Kathy Cook' },
    { age: 71, name: 'Ernest Brooks' },
    { age: 72, name: 'Rose Moore' },
    { age: 71, name: 'Donna Bennett' },
    { age: 25, name: 'Teresa Taylor' },
    { age: 56, name: 'Melissa Young' },
    { age: 24, name: 'Mildred Clark' },
    { age: 32, name: 'Anna Hernandez' },
    { age: 21, name: 'Victor Kelly' },
    { age: 45, name: 'Alan Walker' },
    { age: 37, name: 'Michael Hall' },
    { age: 21, name: 'Howard Sanchez' },
    { age: 33, name: 'Craig Williams' },
    { age: 48, name: 'Dennis Coleman' },
    { age: 74, name: 'Betty Edwards' },
    { age: 27, name: 'Alice Ramirez' },
    { age: 47, name: 'Christina Carter' },
    { age: 58, name: 'Jack Griffin' },
    { age: 62, name: 'Eric Harris' },
    { age: 45, name: 'Walter Robinson' },
    { age: 53, name: 'Michelle Simmons' },
    { age: 40, name: 'Christopher Martin' },
    { age: 69, name: 'Brandon Flores' },
    { age: 29, name: 'Janet Lopez' },
    { age: 69, name: 'Thomas Baker' },
    { age: 60, name: 'Elizabeth Evans' },
    { age: 39, name: 'Gregory Collins' },
    { age: 66, name: 'Scott Price' },
    { age: 34, name: 'Shawn Campbell' },
    { age: 67, name: 'Amy Anderson' },
    { age: 50, name: 'Carol Garcia' },
    { age: 32, name: 'Harry Bell' },
  ]
};
